#! /bin/sh

# Startup programs
sxhkd -c ~/.config/bspwm/sxhkdrc &
picom --config "$HOME/.config/bspwm/picom.conf" &
dunst &
redshift &
polybar -c ~/.config/bspwm/polybar dougbar &

synclient TapButton1=0 &
synclient VertScrollDelta=-40 &
synclient HorizTwoFingerScroll=1 &
synclient HorizScrollDelta=-20 &
synclient TapButton3=0 &
synclient TapButton2=0 &
synclient CoastingFriction=0 &
synclient CoastingSpeed=0 &
synclient RightButtonAreaLeft=0
synclient RightButtonAreaTop=0

hsetroot -solid black
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          5

bspc config focused_border_color "#0081C2"

bspc rule -a Emacs state=tiled
bspc rule -a Gnome-calculator state=floating
bspc rule -a Org.gnome.Nautilus state=floating
bspc rule -a "Syncthing GTK" state=floating

bspc rule -a Thunderbird desktop=^8 follow=off
bspc rule -a Slack desktop=^9 follow=off

bspc config external_rules_command ~/.config/bspwm/external-rules.sh
